version: '3.3'
services:
    alpine-php:
        build:
          context: ..
          dockerfile: docker/Dockerfile
        volumes:
          - '/mnt/nas/data/wiki/mywiki/tiddlers/r/:/svr/data'
        ports:
          - 8082:8080
        network_mode: bridge
        environment:
          - VIRTUAL_HOST=up.wiki.x
          - VIRTUAL_PORT=80
          - UPLOAD_LIMIT=512M
